<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="10.3.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AutoPlex.Peer\AutoPlex.Peer.csproj" />
    <ProjectReference Include="..\AutoPlex.Repository\AutoPlex.Repository.csproj" />
    <ProjectReference Include="..\AutoPlex.Services.Abstraction\AutoPlex.Services.Abstractions.csproj" />
    <ProjectReference Include="..\AutoPlex.Services\AutoPlex.Services.csproj" />
  </ItemGroup>

</Project>
