<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AutoPlex.Repository\AutoPlex.Repository.csproj" />
    <ProjectReference Include="..\AutoPlex.Services.Abstraction\AutoPlex.Services.Abstractions.csproj" />
  </ItemGroup>

</Project>
